config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get  'home/team'
  post 'home/team' => 'home#team'

end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :common, :only => [:index, :team]

  def common
    @hero_name = Faker::Superhero.name # Random Superhero name
    @hero_power = Faker::Superhero.power # Random Superhero power
    @hero_prefix = Faker::Superhero.prefix # Random Superhero prefix
    @corp_title = Faker::Name.title
    @corp_power = Faker::Company.bs
    @corp_power = @corp_power.titleize

    @rand_num = rand(1..1000)
    @set_number = rand(1..4)
    @bg = rand(1..2)

    # Randomly pick our Avatar set
    if @set_number ==1
      @set = "set1"
    elsif @set_number ==2
      @set = "set2"
    elsif @set_number ==3
      @set = "set3"
    else
      @set = "set4"
    end

    # Randomly pick our Background
    if @background == 1
      @background = "bg1"
    else
      @background = "bg2"
    end

    @avatar = Faker::Avatar.image(@rand_num, "300x300", "png", @set, @background)
  end

  def index
    @name = "Xander Alexander"
  end

  def team
    @team_number = params[:team_number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.erb
<div class="panel-body">
  <div class="row">
    <br>
    <div class="col-md-4">
    <%= form_tag home_team_path, :method => 'Post' do %>
      <%= select_tag(:team_number, options_for_select([
        ['1', 1],
        ['2', 2],
        ['3', 3],
        ['4', 4],
        ['5', 5],
        ['6', 6],
        ['7', 7],
        ['8', 8],
        ['9', 9],
        ['10', 10],
        ]), class: 'form-control') %>
        <br>
        <br>
      <%= submit_tag 'Build Your Team!', class: "btn btn-success"%>
    <% end %>

    </form>
    </div

    <div class="col-md-4">

    </div

    <div class="col-md-4">

    </div




  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CASUALE ::: GENERATOR', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home Page', root_path %></li>
        <li><%= link_to 'Create A Team', home_team_path %></li>



        </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show_team.erb
<% @team_number.times do %>

    <div class="row">
      <br>
      <div class="col-md-4">

<% rand_num = rand(1..1000) %>
<% set_number = rand(1..4) %>
<% bg = rand(1..2) %>

<% if set_number ==1 %>
  <% set = "set1" %>
<% elsif set_number ==2 %>
  <% set = "set2" %>
<% elsif set_number ==3 %>
  <% set = "set3" %>
<% else %>
  <% set = "set4" %>
<% end %>

<% if bg == 1 %>
  <% background = "bg1" %>
<% else %>
  <% background = "bg2" %>
<% end %>

<% avatar = Faker::Avatar.image(rand_num, "300x300", "png", set, background) %>

        <img src="<%= avatar %>">
        <br>
        <br>
      </div>

      <div class="col-md-4">
        <h4>Superhero Name:</h4>  <%= Faker::Superhero.prefix %> <%= Faker::Superhero.name %> <%= @hero_name %>
        <br>
        <h4>Superhero Power:</h4> <%= Faker::Superhero.power %>
        <br>
        <h4>Your Undercover Day Job is:</h4> <%= Faker::Name.title %>
        <br>
        <h4>Your Corporate Superpower is:</h4> <%= Faker::Company.bs.titleize %>
      </div>

      <div class="col-md-4">
        <%= button_to "Refresh", root_path, :method => :get %>
      </div>
    </div>
        <div class="row">
          <div class="col-md-12">
            <hr>
          </div>

        </div>
<% end %>

app/views/home/index.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to 'Activate a Superhero', root_path %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <br>
      <div class="col-md-4">
        <img src="<%= @avatar %>">
        <br>
        <br>
      </div>

      <div class="col-md-4">
        <h4>Superhero Name:</h4>  <%= @hero_prefix %> <%= @hero_name %>
        <br>
        <h4>Superhero Power:</h4> <%= @hero_power %>
        <br>
        <h4>Your Undercover Day Job is:</h4> <%= @corp_title %>
        <br>
        <h4>Your Corporate Superpower is:</h4> <%= @corp_power %>
      </div>
      <div class="col-md-4">
        <%= button_to "Refresh", root_path, :method => :get %>
      </div>


    </div>
  </div>
  <div class="panel-footer"><%= link_to 'Create A Team', home_team_path %></div>
</div>

app/views/home/team.html.erb
<br>




<h1>Team</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <% if @team_number > 0 %>
      Your Superhero team
      <% else %>
      How Many Team Members do you want?
      <% end %>
    </h3>
  </div>
  <div class="panel-body">


  <% if @team_number > 0 %>
    <%= render 'home/show_team' %>
  <% else %>
    <%= render 'home/create_team' %>
  <% end %>
  </div>

  <div class="panel-footer"><%= link_to 'Create  a Team', home_team_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Casuale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


<%= render 'home/navbar' %>

<div class="container">
<%= yield %>
<br>
<br>
<center>
Copyright 2018 -casuale- All Rights Reserved
</center>

</div>

</body>
</html>